apiVersion: apps/v1
kind: Deployment #Nous faisons un déploiement 
metadata:
  name: specializations-deployments #Nous donnons le nom du déploiement 
spec:
  replicas: 1   #Permet de choisir le nombre d'environement qu'on lance et de relancer en cas de crash
  selector:
    matchLabels: 
      app: specilaizationservice #defini le nom de mon service
  template: 
    metadata:
      labels:
        app: specializationservice 
    spec: 
      containers:
        - name: specializationservice
          image: max34x/specializationservice:latest  #image de notre service qui se trouve sur docker Hub